#!/usr/bin/env python3
"""Synthesize every sound effect in Multiplication Adventure from scratch.

Written to replace the third-party CC0 audio (Kenney, OpenGameArt/artisticdude,
WobbleBoxx) that shipped through build 6. Those files are byte identical to the
same packs in many other App Store games, which is a plausible cause of the
Guideline 4.3(a) rejection: Apple said the app "shares a similar binary ... as
apps submitted to the App Store by other developers".

Everything here is generated by this script. No samples, no packs, no external
service, no license to honour. The script IS the provenance.

    python3 scripts/make-sfx.py            # writes to build/sfx/
    python3 scripts/make-sfx.py --install  # also copies into Resources/Audio

Design notes: one C-major palette so every cue is consonant with every other;
soft attacks and no harsh transients, because a seven-year-old hears these
hundreds of times; the wrong-answer cue is deliberately gentle, since the app's
whole stance is that a miss costs nothing.
"""
import argparse, math, pathlib, struct, wave
import numpy as np

SR = 44100
ROOT = pathlib.Path(__file__).resolve().parent.parent
OUT = ROOT / "build" / "sfx"
DEST = ROOT / "Sources/App/Resources/Audio"

def n2f(n):                       # semitones from middle C -> Hz
    return 261.625565 * (2 ** (n / 12))

def t(dur):
    return np.linspace(0, dur, int(SR * dur), endpoint=False)

def env(x, a=0.005, d=0.25, s=0.0, r=0.1, hold=0.0):
    """Attack/decay/sustain/release over the length of x."""
    n = len(x); e = np.zeros(n)
    ai, hi, di = int(a*SR), int(hold*SR), int(d*SR)
    ri = max(1, n - ai - hi - di)
    i = 0
    if ai: e[i:i+ai] = np.linspace(0, 1, ai); i += ai
    if hi: e[i:i+hi] = 1.0; i += hi
    if di: e[i:i+di] = np.linspace(1, s, di); i += di
    e[i:i+ri] = np.linspace(s, 0, min(ri, n-i))
    return e

def bell(freq, dur, amp=1.0, decay=6.0, detune=0.0, air=0.0):
    """Struck chime. Deliberately warm: harmonic partials only, steeply rolled
    off, plus a low-pass. An earlier version used inharmonic partials at 2.01x /
    3.02x / 4.7x, which beat against each other and put a bright spike near 5 kHz
    on top of a cue that fires on every correct answer. It was harsh."""
    x = t(dur)
    y = (np.sin(2*np.pi*freq*x)
         + 0.20*np.sin(2*np.pi*freq*2*x)
         + 0.05*np.sin(2*np.pi*freq*3*x))
    if air:
        y += air*np.sin(2*np.pi*freq*4*x)
    if detune:
        y += 0.5*np.sin(2*np.pi*freq*(1+detune)*x)
    y = y * np.exp(-decay*x) * env(x, a=0.008, d=dur*0.9, r=dur*0.1)
    return amp * lowpass(y, 3800)

def tri(freq, dur, amp=1.0):
    x = t(dur)
    return amp * (2/np.pi) * np.arcsin(np.sin(2*np.pi*freq*x))

def noise(dur, amp=1.0, seed=0):
    rng = np.random.default_rng(seed)
    return amp * rng.standard_normal(int(SR*dur))

def lowpass(x, cutoff):
    """One-pole low-pass; cutoff may be a scalar or a per-sample array."""
    c = np.full(len(x), cutoff, dtype=float) if np.isscalar(cutoff) else cutoff
    a = np.clip(1 - np.exp(-2*np.pi*c/SR), 0, 1)
    y = np.zeros(len(x)); prev = 0.0
    for i in range(len(x)):
        prev += a[i] * (x[i] - prev); y[i] = prev
    return y

def lowpass2(x, cutoff):
    """Two cascaded one-poles, -12 dB/oct. A single pole leaks far too much hiss
    through for noise-based cues; the star slam measured 52% of its energy above
    3 kHz even with a 3.2 kHz one-pole on it."""
    return lowpass(lowpass(x, cutoff), cutoff)

def sweep(f0, f1, dur, kind="sin", amp=1.0):
    x = t(dur)
    k = (f1/f0) ** (1/max(dur, 1e-6))
    phase = 2*np.pi*f0*((k**x - 1)/math.log(k)) if abs(k-1) > 1e-9 else 2*np.pi*f0*x
    w = np.sin(phase) if kind == "sin" else (2/np.pi)*np.arcsin(np.sin(phase))
    return amp * w

def place(base, part, at=0.0, gain=1.0):
    i = int(at*SR)
    n = min(len(part), len(base)-i)
    if n > 0: base[i:i+n] += gain * part[:n]
    return base

def mix(*parts):
    """Sum signals of differing lengths, zero-padding to the longest."""
    n = max(len(p) for p in parts)
    out = np.zeros(n)
    for p in parts:
        out[:len(p)] += p
    return out

def tail(x, amount=0.22, delay=0.055, reps=4):
    """Cheap ambience: a few decaying delayed copies."""
    y = x.copy()
    for r in range(1, reps+1):
        d = int(delay*r*SR)
        if d < len(x): y[d:] += (amount**r) * x[:len(x)-d]
    return y

def finish(x, peak=0.82, fade=0.008):
    x = np.asarray(x, dtype=float)
    f = int(fade*SR)
    if len(x) > 2*f:
        x[:f] *= np.linspace(0, 1, f); x[-f:] *= np.linspace(1, 0, f)
    m = np.max(np.abs(x)) or 1.0
    x = x / m * peak
    return np.tanh(x * 1.08) * 0.97          # gentle soft-clip, no harsh edges

def save(name, x):
    OUT.mkdir(parents=True, exist_ok=True)
    d = (np.clip(finish(x), -1, 1) * 32767).astype("<i2")
    with wave.open(str(OUT / f"{name}.wav"), "wb") as f:
        f.setnchannels(1); f.setsampwidth(2); f.setframerate(SR)
        f.writeframes(d.tobytes())
    return OUT / f"{name}.wav"

# ---------------------------------------------------------------- the cues

def correct(offset=0, dur=0.46, sparkle=False):
    """Ascending three-note chime, streak variants stepping up the C-major scale.

    Pitched at C5-E5-G5 rather than an octave higher. The first pass sat at C6
    and the streak-8 variant at G6, which pushed most of the energy past 3 kHz:
    thin, piercing, and unpleasant on a sound a child triggers hundreds of times.
    """
    notes = [0, 4, 7]                         # C E G, one octave lower than v1
    y = np.zeros(int(SR*dur))
    for i, n in enumerate(notes):
        y = place(y, bell(n2f(n+offset+12), dur*0.85, amp=0.58-0.05*i, decay=6.5),
                  at=0.055*i)
    if sparkle:
        for i, n in enumerate([19, 23, 26]):  # was [31,35,38]: an octave down, quieter
            y = place(y, bell(n2f(n+offset), 0.20, amp=0.07, decay=15), at=0.13+0.045*i)
    return lowpass(tail(y, 0.16, 0.05, 3), 4200)

def wrong(dur=0.42):
    """Two soft descending notes. Never harsh: a miss costs nothing in this app."""
    y = np.zeros(int(SR*dur))
    for i, n in enumerate([7, 2]):
        x = t(0.22)
        tone = (np.sin(2*np.pi*n2f(n)*x) + 0.25*np.sin(2*np.pi*n2f(n)*2*x))
        y = place(y, tone*np.exp(-7*x)*env(x, a=0.012, d=0.2), at=0.13*i, gain=0.5)
    return lowpass(y, 1500)

def key(dur=0.06):
    """Number pad tap. The most repeated sound in the app by a wide margin, so it
    is mostly a soft wooden thock rather than a click: a quiet filtered transient
    for snap, and a low body tone carrying the weight."""
    x = t(dur)
    click = lowpass2(noise(dur, 0.30, seed=7) * np.exp(-120*x), 2000)
    body  = (np.sin(2*np.pi*620*x) + 0.3*np.sin(2*np.pi*930*x)) * np.exp(-48*x) * 0.75
    return lowpass(click + body, 3000)

def boss_hit(dur=0.5):
    x = t(dur)
    thump = np.sin(2*np.pi*np.clip(150*np.exp(-11*x), 35, None)*x) * np.exp(-13*x) * 0.95
    crack = lowpass2(noise(dur, 0.75, seed=3) * np.exp(-34*x), 2200)
    ring  = bell(n2f(-5), dur*0.8, amp=0.22, decay=11)
    return mix(thump, crack, ring)

def boss_defeat(dur=2.6):
    y = np.zeros(int(SR*dur))
    y = place(y, sweep(760, 80, 1.1, amp=0.34) * np.exp(-2.2*t(1.1)), at=0.0)
    y = place(y, lowpass(noise(0.9, 0.5, seed=11) * np.exp(-4.5*t(0.9)), 900), at=0.0)
    rumble = np.sin(2*np.pi*46*t(1.5)) * np.exp(-2.6*t(1.5)) * 0.5
    y = place(y, rumble, at=0.05)
    for i, n in enumerate([0, 4, 7, 12]):     # resolving major chord
        y = place(y, bell(n2f(n+12), 1.5, amp=0.34-0.04*i, decay=2.4), at=0.85+0.075*i)
    return tail(y, 0.26, 0.09, 4)

def world_unlock(dur=1.7):
    y = np.zeros(int(SR*dur))
    rise = sweep(220, 1500, 0.75, amp=0.28) * env(t(0.75), a=0.25, d=0.5)
    y = place(y, lowpass(rise, np.linspace(700, 6500, int(SR*0.75))), at=0.0)
    shimmer = lowpass2(noise(0.75, 0.30, seed=5), np.linspace(450, 5200, int(SR*0.75)))
    y = place(y, shimmer*env(t(0.75), a=0.3, d=0.45), at=0.0, gain=0.5)
    for i, n in enumerate([12, 16, 19, 24]):
        y = place(y, bell(n2f(n), 0.95, amp=0.45-0.05*i, decay=4.2), at=0.70+0.06*i)
    return tail(y, 0.22, 0.075, 4)

def milestone(dur=1.3):
    y = np.zeros(int(SR*dur))
    for i, n in enumerate([12, 16, 19, 24, 28]):
        y = place(y, bell(n2f(n), 0.75, amp=0.42-0.045*i, decay=6.0), at=0.075*i)
    tw = np.zeros(int(SR*dur))
    rng = np.random.default_rng(21)
    for k in range(14):
        at = 0.18 + 0.075*k + rng.uniform(-0.02, 0.02)
        tw = place(tw, bell(n2f(int(rng.choice([24, 28, 31, 33, 36]))), 0.18, amp=0.08, decay=19), at=at)
    return tail(y + tw, 0.2, 0.06, 3)

def complete(dur=3.2):
    """Full fanfare: I - IV - V - I, with a sparkle tail."""
    y = np.zeros(int(SR*dur))
    chords = [([0, 4, 7], 0.00), ([5, 9, 12], 0.42), ([7, 11, 14], 0.84), ([12, 16, 19, 24], 1.30)]
    for notes, at in chords:
        for i, n in enumerate(notes):
            length = 1.7 if at > 1.2 else 0.55
            y = place(y, bell(n2f(n+12), length, amp=0.40-0.04*i, decay=3.0 if at > 1.2 else 5.5),
                      at=at + 0.028*i)
    rng = np.random.default_rng(4)
    for k in range(20):
        y = place(y, bell(n2f(int(rng.choice([24, 28, 31, 36, 40]))), 0.22, amp=0.07, decay=17),
                  at=1.45 + 0.075*k + rng.uniform(-0.02, 0.02))
    return tail(y, 0.26, 0.085, 4)

def phase_zap(dur=0.55):
    x = t(dur)
    flutter = 1 + 0.5*np.sin(2*np.pi*38*x) + 0.25*np.sin(2*np.pi*133*x)
    body = np.sin(2*np.pi*np.cumsum(620*flutter)/SR) * np.exp(-7.5*x) * 0.55
    fizz = lowpass2(noise(dur, 0.6, seed=13) * np.exp(-11*x), np.linspace(4200, 900, len(x)))
    return body + fizz*0.55

def star_slam(dur=0.95):
    y = np.zeros(int(SR*dur))
    wh = lowpass2(noise(0.3, 0.55, seed=9), np.linspace(380, 3600, int(SR*0.3)))
    y = place(y, wh*env(t(0.3), a=0.2, d=0.1), at=0.0)
    xi = t(0.4)
    y = place(y, np.sin(2*np.pi*np.clip(190*np.exp(-9*xi), 45, None)*xi)*np.exp(-11*xi)*0.9, at=0.26)
    y = place(y, lowpass2(noise(0.25, 0.6, seed=17)*np.exp(-26*t(0.25)), 2500), at=0.26)
    for i, n in enumerate([19, 23, 26]):
        y = place(y, bell(n2f(n), 0.55, amp=0.26-0.03*i, decay=9), at=0.30+0.045*i)
    return tail(y, 0.2, 0.06, 3)

CUES = {
 "sfx_correct":      lambda: correct(0),
 "sfx_correct2":     lambda: correct(2, dur=0.42),
 "sfx_correct3":     lambda: correct(4, dur=0.38),
 "sfx_correct4":     lambda: correct(7, dur=0.36, sparkle=True),
 "sfx_wrong":        wrong,
 "sfx_key":          key,
 "sfx_world_unlock": world_unlock,
 "sfx_milestone":    milestone,
 "sfx_complete":     complete,
 "sfx_boss_hit":     boss_hit,
 "sfx_boss_defeat":  boss_defeat,
 "sfx_phase_zap":    phase_zap,
 "sfx_star_slam":    star_slam,
}

if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("--install", action="store_true", help="copy into Resources/Audio")
    args = ap.parse_args()
    for name, fn in CUES.items():
        p = save(name, fn())
        with wave.open(str(p)) as f:
            print(f"  {name:<20} {f.getnframes()/f.getframerate():.2f}s  {p.stat().st_size/1024:6.1f} KB")
    if args.install:
        import shutil
        for name in CUES:
            shutil.copy(OUT / f"{name}.wav", DEST / f"{name}.wav")
        print(f"\ninstalled {len(CUES)} files into {DEST}")
